Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -16,3 +16,40 @@ jobs:
       run: |
         gem install bundler
         bundle install --jobs 4 --retry 3
+    - name: Publish
+      run: |
+        bundle exec jekyll build -d build
+        echo "#################################################"
+        echo "Jekyll build done"
+        
+        cd build
+
+        # No need to have GitHub Pages to run Jekyll
+        touch .nojekyll
+
+        echo "#################################################"
+        echo "Now publishing"
+        if [[ -z "${JEKYLL_PAT}" ]]; then
+          TOKEN=${GITHUB_TOKEN}
+        else 
+          TOKEN=${JEKYLL_PAT}
+        fi
+        
+        remote_branch="master"
+
+        if [ "${GITHUB_REF}" == "refs/heads/${remote_branch}" ]; then
+          echo "Cannot publish on branch ${remote_branch}"
+          exit 1
+        else
+          echo "Pushing on branch ${remote_branch}"
+        fi
+
+        remote_repo="https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" && \
+        git init && \
+        git config user.name "${GITHUB_ACTOR}" && \
+        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
+        git add . && \
+        git commit -m 'jekyll build from Action' && \
+        git push --force $remote_repo master:$remote_branch && \
+        rm -fr .git && \
+        cd ..
